name: "${PROJECT_NAME:-regatta-tracker}"
services:
  app:
    image: "public.ecr.aws/rpungello/regatta-tracker:${IMAGE_TAG:-latest}"
    env_file: rt.env
    ports:
      - '${WEB_PORT:-80}:80'
    restart: unless-stopped
  nightwatch:
    image: "laravelphp/nightwatch-agent:v1"
    environment:
      - NIGHTWATCH_TOKEN=${NIGHTWATCH_TOKEN}
    restart: unless-stopped
